### ISSUE TITLE
Moderator commands

### ISSUE THREAD

**Issue by TheLavaPhoenix** [shadowolfyt/Gamers-Alliance-Bot#1]
Maybe add moderator commands with a custom prefix?

**Comment by shadowolfyt** [comment]
Custom prefix won't be needed, we can restrict everything with permissions.

**Comment by shadowolfyt** [comment]
List me some command you'd like to have.

**Comment by TheLavaPhoenix** [comment]
well basic moderator commands: -help -ban -kick -mute -clear

**Comment by shadowolfyt** [comment]
Requested commands have been added.
